plugins:
  - jekyll-toc
  - jekyll-feed
  - jekyll-katex

url: stealthmate.github.io
baseurl: /

exclude:
- Gemfile
- Gemfile.lock
- excluded
- vendor
- makefile
- docs_local
- docs
- ignore

toc:
  min_level: 1
  max_level: 3

theme: minima

destination: docs

feed:
  collections:
    - posts

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  input: GFM
  math_engine: katex

katex:
  rendering_options:
    # Default KaTeX rendering options. See https://github.com/Khan/KaTeX#rendering-options
    throw_error: true                       # throwOnError - set to false if you want rendering to output error as text rather than a build error
    error_color: "#cc0000"                  # errorColor
    global_group: true
