plugins:
  - jekyll-toc
  - jekyll-feed

url: stealthmate.github.io
baseurl: /

exclude:
- Gemfile
- Gemfile.lock
- excluded
- vendor
- makefile
- docs_local
- docs
- ignore

toc:
  min_level: 1
  max_level: 3

theme: minima

destination: docs

feed:
  collections:
    - posts

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  input: GFM
  math_engine: nil
